linux-live build corrections

diff --git a/live-base/build b/live-base/build
--- a/live-base/build
+++ b/live-base/build
@@ -22,9 +22,9 @@ LIVECDNAME="`echo $LIVECDNAME | tr -d ' '`"
 . ./install
 
 # search for kernel
-VMLINUZ=/boot/vmlinuz
+VMLINUZ=$ROOT/boot/vmlinuz
 if [ -L "$VMLINUZ" ]; then VMLINUZ=`readlink -f $VMLINUZ`; fi
-if [ "`ls $VMLINUZ 2>>$DEBUG`" == "" ]; then echo "cannot find $VMLINUZ"; exit 1; fi
+if [ "`ls $VMLINUZ 2>>$DEBUG`" = "" ]; then echo "cannot find $VMLINUZ"; exit 1; fi
 
 header "Creating LiveCD from your Linux"
 echo "some debug information can be found in $DEBUG"
@@ -32,17 +32,12 @@ echo "some debug information can be found in $DEBUG"
 mkdir -p $CDDATA/$LIVECDNAME/{base,modules,optional,rootcopy,tools}
 
 echo "copying cd-root to $CDDATA, using kernel from $VMLINUZ"
-cp -R cd-root/boot $CDDATA
-for i in isolinux syslinux; do
-   cat cd-root/boot/$i/$i.cfg | sed -r "s/LABEL linux/LABEL $LIVECDNAME/" | sed -r "s/DEFAULT linux/DEFAULT $LIVECDNAME/" > $CDDATA/boot/$i/$i.cfg
-done
-mv $CDDATA/boot/dos/linux.bat $CDDATA/boot/dos/${LIVECDNAME:0:8}.bat
-cat cd-root/boot/dos/readme.txt | sed -r "s/LINUX.BAT/"${LIVECDNAME:0:8}.bat"/" > $CDDATA/boot/dos/readme.txt
+cp -a cd-root/boot $CDDATA
 
 mkdir -p $CDDATA/$LIVECDNAME
 cp -R cd-root/linux/* $CDDATA/$LIVECDNAME
 cp tools/* $CDDATA/$LIVECDNAME/tools
-cp -R DOC/LICENSE $CDDATA/$LIVECDNAME
+cp -R DOC/* $CDDATA/$LIVECDNAME
 cp $VMLINUZ $CDDATA/boot/vmlinuz
 
 echo "creating initrd image..."
